registries:
  - domain:     docker.io
    username:   123
    password:   123
  - domain:         ghcr.io
    username:       owner
    password_file:  /run/secrets/ghcr_token
  - domain:     custom_registry.tld
    username:   321
    password_env: CUSTOM_REGISTRY_PASSWORD
    insecure:   true
