name: Build (Latest)

on:
  push:
    branches:
      - master
    paths:
      - .github/workflows/build.yml
      - .github/workflows/build_latest.yml
      - .github/workflows/test.yml
      - main/**
      - internal/**
      # read by the tests
      - examples/**
      - Dockerfile
      - .dockerignore
      - go.mod
      - go.sum

jobs:
  build:
    uses: ./.github/workflows/build.yml
    permissions:
      contents: read
      packages: write
    with:
      tags: type=raw,value=latest
